--
SELECT 1+1 FROM STUDENT s WHERE 1=1;

SELECT 1+1 FROM DUAL WHERE 'SQL'='SQL';

CREATE TABLE EX_TYPE(
	C CHAR(7), 
	v VARCHAR2(7),
	N NUMBER(5,2)
	)

DROP TABLE EX_TYPE;

SELECT * FROM EX_TYPE;

INSERT INTO EX_TYPE VALUES( '1','sql',1);
INSERT INTO EX_TYPE VALUES( '100','sql',100);
INSERT INTO EX_TYPE VALUES( '20','sql',20);
INSERT INTO EX_TYPE VALUES( '2','sql',2);
INSERT INTO EX_TYPE VALUES( '3','sql',30);

DELETE FROM EX_TYPE WHERE V = 'sql';

UPDATE SET EX_TYPE WHERE c = 'sql2';

SELECT  * FROM  EX_TYPE WHERE  C=V ||'    ';


SELECT 3.14+1 FROM DUAL;


SELECT * FROM STUDENT s ;

SELECT SYSDATE FROM DUAL;

SELECT STUDENT.*, ROWID FROM STUDENT ;


SELECT ROWNUM,STUDENT.*,ROWID FROM STUDENT WHERE GRADE <= 5;


SELECT * FROM STUDENT ;
-- 학생 테이블에서 1학년 학생의 학번 이름 학과번호 조회

SELECT STUDNO,NAME,DEPTNO,GRADE FROM STUDENT WHERE GRADE  = 1;

-- 학번 이름 학년 학과번호 몸구게 조회 , 학생테이블에서 , 단 70이상이어야한다
SELECT STUDNO ,NAME ,DEPTNO ,GRADE ,WEIGHT FROM STUDENT WHERE  WEIGHT >=70; 
-- 70이상 1학년
SELECT STUDNO ,NAME ,DEPTNO ,GRADE ,WEIGHT FROM STUDENT WHERE GRADE = 1 AND WEIGHT >=70;
-- 70이상 혹은 1학년
SELECT STUDNO ,NAME ,DEPTNO ,GRADE ,WEIGHT FROM STUDENT WHERE GRADE = 1 OR WEIGHT >=70;

-- 학번 이름 몸무게, 체중이 50이상 70이하인 사람만
SELECT NAME,WEIGHT,STUDNO FROM STUDENT WHERE WEIGHT BETWEEN 50 AND 70 AND GRADE  = 1;

-- 학생증 이름, 생년월일 출력,81년에서 83년 사이에 태어난

SELECT NAME,BIRTHDATE FROM STUDENT WHERE BIRTHDATE BETWEEN '81/01/01' AND '83/12/31';

--이름,학년,학과번호 조회 ,102번,201번학과만

SELECT NAME,GRADE,DEPTNO FROM STUDENT WHERE DEPTNO IN (102,201);  
-- 학생증 이름, 생년월일 출력,81년에서 83년 사이에 태어난

SELECT NAME,TO_CHAR(BIRTHDATE,'YY') FROM STUDENT WHERE TO_CHAR(BIRTHDATE,'YY') IN(81,82,83) ;


-- 이름,학년,학과번호 조회,김씨만

SELECT NAME,GRADE,DEPTNO FROM STUDENT WHERE NAME LIKE '%김%';
-- 모든숫자에 연산 null 하면 null 2/0같은 형태는 오류
SELECT 2/NULL FROM DUAL;

--교수 테이블의 이름,직급,보직수당 조회
SELECT NAME,POSITION,COMM FROM PROFESSOR p ;

----교수 테이블의 이름,직급,보직수당 조회단 수당이있는사람만
SELECT NAME,POSITION,COMM FROM PROFESSOR WHERE COMM IS NOT NULL ;

-- 교수이름,급여,수당,급여+수당 조회

SELECT NAME,POSITION,COMM,COMM+SAL,NVL(COMM,0) + SAL AS SALCOM  ,NVL2(COMM,SAL+COMM,SAL) AS Mvl FROM PROFESSOR ;

-- NVL