SELECT * FROM TAB;



SELECT * FROM STUDENT s ORDER BY STUDNO ASC  ;

SELECT DEPTNO,DNAME FROM DEPARTMENT d ;

SELECT DEPTNO,COUNT(*),AVG(HEIGHT) FROM STUDENT s  WHERE DEPTNO  < 201 GROUP BY DEPTNO HAVING COUNT(*)>=5 ;

SELECT * FROM STUDENT ORDER BY GRADE DESC,STUDNO ;

SELECT DEPTNO ,COUNT(*) FROM STUDENT s GROUP BY DEPTNO;

--RESULT SET 행 TUPLE;

SELECT DISTINCT DEPTNO,STUDNO FROM STUDENT GROUP BY DEPTNO,STUDNO  ;


SELECT DISTINCT DEPTNO,GRADE FROM STUDENT;

-- 부서테이블 부서이름은 "부서이름" 부서번호는 "부서번호"
SELECT DNAME AS "부서이름",DEPTNO AS "부서번호" FROM DEPARTMENT; 

SELECT * FROM  STUDENT s WHERE HEIGHT >= 170 AND WEIGHT >= 70;

-- 학생 테이블에서 학번과 이름을 연결하여 STUDENT라는 별칭을 붙인 결과 조회
SELECT STUDNO || ' ' || NAME STUDENT, CONCAT(STUDNO, NAME) FROM STUDENT;